# Generated by Django 4.2.21 on 2025-05-31 21:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content_type', models.CharField(choices=[('quest_background', 'Quest Background'), ('card_art', 'Card Art'), ('character_portrait', 'Character Portrait'), ('story_text', 'Story Text')], max_length=50)),
                ('prompt', models.TextField()),
                ('generated_text', models.TextField(blank=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('generation_parameters', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
